# Generated by Django 4.2.6 on 2023-10-19 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MyBlog',
            new_name='Blog',
        ),
        migrations.AddField(
            model_name='author',
            name='blog',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog'),
        ),
    ]
