# Generated by Django 4.2.6 on 2023-10-19 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='blog',
        ),
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog_app.author'),
        ),
    ]
