# Generated by Django 4.2.6 on 2023-10-19 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_remove_author_blog_blog_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.AddField(
            model_name='author',
            name='blog',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='blog_app.blog'),
        ),
    ]
