# Generated by Django 4.2.6 on 2023-11-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0011_alter_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
