# Generated by Django 4.2.6 on 2023-11-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0019_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='images/authors/'),
        ),
    ]
