# Generated by Django 4.2.6 on 2023-11-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0022_alter_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='name',
            field=models.CharField(default='Untitled', max_length=200),
        ),
    ]
