# Generated by Django 4.2.6 on 2023-11-24 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0029_author_user_blog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.OneToOneField(default='Anonymous', on_delete=django.db.models.deletion.CASCADE, to='blog_app.author'),
        ),
    ]
