# Generated by Django 4.2.6 on 2023-11-24 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0031_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='theme',
            field=models.CharField(choices=[('BO', 'Blood Orange')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='blogPosts', to='blog_app.blog'),
        ),
    ]
