# Generated by Django 4.2.6 on 2023-11-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0032_blog_theme_alter_post_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(choices=[('BO', 'Blood Orange')], default=None, max_length=200, null=True),
        ),
    ]
