# Generated by Django 4.2.6 on 2023-11-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0033_alter_blog_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(choices=[('None', 'None'), ('BO', 'Blood Orange')], default=None, max_length=200, null=True),
        ),
    ]
