# Generated by Django 4.2.6 on 2023-11-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0037_alter_blog_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='theme',
            field=models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='theme',
            field=models.CharField(choices=[('Light', 'Light'), ('BO', 'Blood Orange'), ('LL', 'Lemon Lime'), ('UH', 'Ube Halaya'), ('Dark', 'Dark')], default=None, max_length=200, null=True),
        ),
    ]
