name: Django Tests for CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout repository under $GITHUB_WORKSPACE for job access
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
           python-version: 3.11
      - name: Install requirements
        run: |
            pip install -r requirements.txt
      - name: Install Selenium and geckodriver
        run: |
            pip install selenium
            pip install geckodriver-autoinstaller
      - name: Run tests
        run: |
            python manage.py test
